### ISSUE TITLE
set_time_limit will only work without safe mode 

### ISSUE THREAD

**Issue by larsroettig** [Recolize/recolize-recommendations-magento2#3]
Hi, 
I found a posbile bug because set_time_limit will only work without save mode. 

http://www.php.net/set_time_limit

https://github.com/Recolize/recommendation-engine-magento2/blob/fec1689d5bfd7ecbe50bc4dc8ac2cb366e26ee20/Model/Feed.php#L126

**Comment by ma4nn** [comment]
Hi @larsroettig,

thanks very much for your report.

As far as I can see this should be no problem because
1. PHP Safe Mode is removed since PHP 5.4.0 and Magento 2 has a minimum requirement of PHP 5.5 and
2. if Safe Mode would be active the `set_time_limit()` command just had no effect so the feed generation does not abort.

So I'm closing this ticket if you agree.

Best regards,
Christoph
